### ISSUE TITLE
theme color change

### ISSUE THREAD

**Issue by sk16** [freshdesk/hotline-phonegap#16]
is there is any way to change in theme color of chat conversation/FAQ  via API or changing some .js/java files?

**Comment by jcsrb** [comment]
http://support.hotline.io/support/solutions/articles/221190-hotline-android-theming-and-customization
http://support.hotline.io/support/solutions/articles/221187-hotline-ios-theming-and-customization-guide

**Comment by hrishikesh-p** [comment]
Thanks @jcsrb 

@sk16 I am closing this issue. Do drop us an email at support@hotline.io if you need any assistance with the theming.

**Comment by sk16** [comment]
thanks @jcsrb  for the solution,

@hrishikesh-p  if its possible can you make the api for theme color in future. It will help us in code maintainability.

Thanks,
