### ISSUE TITLE
Unable to  initialize sdk

### ISSUE THREAD

**Issue by ranvirgorai** [freshdesk/hotline-phonegap#2]
window.Hotline.init(), not working
on calling any method showing, sdk not initialize.

**Comment by vaibhavn1** [comment]
Try calling like this

window.Hotline.init({
            appId       : "appid",
            appKey      : "appkey",
            domain      : "app.hotline.io"
        });

**Comment by ranvirgorai** [comment]
Still Not Working... I tried this method... Showing same error... if us did successfully plz share code snapshot of controller.js and app.js

**Comment by rsquare2014** [comment]
@ranvirjsr  We have a fix for this issue out in v0.4.1 Please let me know if it still persists.

**Comment by rsquare2014** [comment]
closing this, please feel free to re-open if the issue is not resolved.

**Comment by mj6uc** [comment]
This is still an issue - ionic 3 app 
* installed plugin
no way to init the SDK...
