### ISSUE TITLE
Cant able to build the apk file

### ISSUE THREAD

**Issue by muhsin-k** [freshdesk/hotline-phonegap#20]
I am developing a mobile application using ionic.After adding the plugin, the building is not working.

![snap](https://cloud.githubusercontent.com/assets/12408980/20592563/e828019c-b1f3-11e6-9201-2fdadfbc8eb7.png)

Also i am having the latest version of android SDK. What are the possible cases?

**Comment by hrishikesh-p** [comment]
The error seems to be a network issue preventing access to jitpack servers. Are you using the standard Oracle Java SDK  ? It is possible that a root cert is missing causing the HTTPS authentication failure.

**Comment by rsquare2014** [comment]
Specific versions of Gradle need java 8 can you please check this with Java 8?

**Comment by muhsin-k** [comment]
@hrishikesh-p I have tried many times

@rsquare2014 I am using java 1.8 version

![java](https://cloud.githubusercontent.com/assets/12408980/20615862/90d4fc36-b303-11e6-802b-c6ccdc4aa714.png)

**Comment by hrishikesh-p** [comment]
Please refer to JitPack instructions on fixing this known issue on linux here -> https://jitpack.io/docs/FAQ/

`Upgrade to Gradle 2.11 - Run Gradle with Java 8`

**Comment by muhsin-k** [comment]
@hrishikesh-p  I am using the gradle  2.11 version
![gradel](https://cloud.githubusercontent.com/assets/12408980/20617014/40d85102-b30c-11e6-8c76-020ad70c3114.png)

**Comment by rsquare2014** [comment]
Hey, it looks like your gradle is using JVM version 1.7.0_111 so can you please update that to use v1.8? I think that should sort the issue.

**Comment by muhsin-k** [comment]
It worked.Thanks
