### ISSUE TITLE
how to use in ionic2 suggestion

### ISSUE THREAD

**Issue by yogeshwar607** [freshdesk/hotline-phonegap#21]
Hi, 
please include note in your documentation for how to use this plugin in ionic2.

initializeApp() {
    this.platform.ready().then(() => {
       (<any>window).Hotline.init({
      appId: "",
      appKey: "",
      agentAvatarEnabled: true,
      cameraCaptureEnabled: false,
      voiceMessagingEnabled: true,
      pictureMessagingEnabled: true
    })
});

**Comment by rsquare2014** [comment]
thanks for this suggestion, we will look into it and create  a documentation after we test on ionic.

**Comment by imromec** [comment]
It's crashing when i use init function. Do not know why.

**Comment by imromec** [comment]
I used following code,

`(<any>window).Hotline.init({
      appId: "b9c2537f-0490-4867-9ef0-15565a521445",
      appKey: "eba2fd74-8710-4493-b291-dece8dc43fc4",
      agentAvatarEnabled: true,
      cameraCaptureEnabled: false,
      voiceMessagingEnabled: true,
      pictureMessagingEnabled: true
      })
    });`

**Comment by imromec** [comment]
I used following code,

`(<any>window).Hotline.init({
      appId: "*****",
      appKey: "******",
      agentAvatarEnabled: true,
      cameraCaptureEnabled: false,
      voiceMessagingEnabled: true,
      pictureMessagingEnabled: true
      })
    });`
