### ISSUE TITLE
App is Crashing, Unable to Initialize SDK (Cordova in Ionic2)

### ISSUE THREAD

**Issue by imromec** [freshdesk/hotline-phonegap#25]

**Comment by imromec** [comment]
![screen shot 2017-02-21 at 12 48 59 pm](https://cloud.githubusercontent.com/assets/5548820/23156470/09020914-f83d-11e6-80e0-6896e06a9af3.png)

**Comment by rsquare2014** [comment]
This issue has been resolved at support@hotline.io.
