### ISSUE TITLE
App is crashing when click faq item

### ISSUE THREAD

**Issue by muhsin-k** [freshdesk/hotline-phonegap#29]
I need to display FAQ section[Dont need to show contact us and search button ] only in my app.

Here is my code

**Javascript**
```
showFaq = window.Hotline.showFAQs({
    showFaqCategoriesAsGrid: true,
    showContactUsOnAppBar: false,
    showContactUsOnFaqScreens: false,
    showContactUsOnFaqNotHelpful: false
});
document.getElementById("launch_faq").onclick = showFaq;
```
**Html**
```
<div id="launch_faq">
</div>
```

So I am able to see the FAQ secion in my app.
![screenshot_2017-05-04-15-06-33](https://cloud.githubusercontent.com/assets/12408980/25702851/870838b0-30f0-11e7-9d18-c67d7a2f1074.png)

After clicking on the first item.The app is crashing.

![screenshot_2017-05-04-15-06-42](https://cloud.githubusercontent.com/assets/12408980/25702877/b5cb62da-30f0-11e7-945a-8505df2666c4.png)

Please help me ?

**Comment by rsquare2014** [comment]
Can you share your crash logs with us?

**Comment by muhsin-k** [comment]
I have removed this plugin and created a custom module in NodeJs.Thanks

**Comment by jasonandress** [comment]
I'm getting this same issue.
Crash Logs:
07-05 18:37:53.984  7673  7673 E AndroidRuntime: java.lang.UnsupportedOperationException: This is not supported, use MenuItemCompat.setOnActionExpandListener()
07-05 18:37:53.984  7673  7673 E AndroidRuntime:        at android.support.v7.internal.view.menu.MenuItemImpl.setOnActionExpandListener(MenuItemImpl.java:740)
07-05 18:37:53.984  7673  7673 E AndroidRuntime:        at android.support.v4.view.MenuItemCompat.setOnActionExpandListener(MenuItemCompat.java:363)
07-05 18:37:53.984  7673  7673 E AndroidRuntime:        at com.freshdesk.hotline.activity.ArticleListActivity.onCreateOptionsMenu(Unknown Source)
07-05 18:37:53.984  7673  7673 E AndroidRuntime:        at android.app.Activity.onCreatePanelMenu(Activity.java:3157)
07-05 18:37:53.984  7673  7673 E AndroidRuntime:        at android.support.v4.app.FragmentActivity.onCreatePanelMenu(FragmentActivity.java:320)
07-05 18:37:53.984  7673  7673 E AndroidRuntime:        at android.support.v7.internal.view.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:84)
07-05 18:37:53.984  7673  7673 E AndroidRuntime:        at android.support.v7.app.AppCompatDelegateImplBase$AppCompatWindowCallbackBase.onCreatePanelMenu(AppCompatDelegateImplBase.java:275)
07-05 18:37:53.984  7673  7673 E AndroidRuntime:        at android.support.v7.app.AppCompatDelegateImplV7.preparePanel(AppCompatDelegateImplV7.java:1117)
07-05 18:37:53.984  7673  7673 E AndroidRuntime:        at android.support.v7.app.AppCompatDelegateImplV7.doInvalidatePanelMenu(AppCompatDelegateImplV7.java:1399)
07-05 18:37:53.984  7673  7673 E AndroidRuntime:        at android.support.v7.app.AppCompatDelegateImplV7.access$100(AppCompatDelegateImplV7.java:89)
07-05 18:37:53.984  7673  7673 E AndroidRuntime:        at android.support.v7.app.AppCompatDelegateImplV7$1.run(AppCompatDelegateImplV7.java:126)
07-05 18:37:53.984  7673  7673 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:751)
07-05 18:37:53.984  7673  7673 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:95)
07-05 18:37:53.984  7673  7673 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:154)
07-05 18:37:53.984  7673  7673 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6154)
07-05 18:37:53.984  7673  7673 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
07-05 18:37:53.984  7673  7673 E AndroidRuntime:        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
07-05 18:37:53.984  7673  7673 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)
