### ISSUE TITLE
Build Command Faild

### ISSUE THREAD

**Issue by sisodiakaran** [freshdesk/hotline-phonegap#3]
Hi,

I was trying to build the package but Build failed with an exception. Below is my Gradle Console log:

`Executing tasks: [:assembleDebug]

Configuration on demand is an incubating feature.
:preBuild
:compileDebugNdk UP-TO-DATE
:preDebugBuild
:checkDebugManifest
:CordovaLib:compileLint
:CordovaLib:copyDebugLint UP-TO-DATE
:CordovaLib:mergeDebugProguardFiles UP-TO-DATE
:CordovaLib:preBuild
:CordovaLib:preDebugBuild
:CordovaLib:checkDebugManifest
:CordovaLib:prepareDebugDependencies
:CordovaLib:compileDebugAidl UP-TO-DATE
:CordovaLib:compileDebugRenderscript UP-TO-DATE
:CordovaLib:generateDebugBuildConfig UP-TO-DATE
:CordovaLib:generateDebugAssets UP-TO-DATE
:CordovaLib:mergeDebugAssets UP-TO-DATE
:CordovaLib:generateDebugResValues UP-TO-DATE
:CordovaLib:generateDebugResources UP-TO-DATE
:CordovaLib:packageDebugResources UP-TO-DATE
:CordovaLib:processDebugManifest UP-TO-DATE
:CordovaLib:processDebugResources UP-TO-DATE
:CordovaLib:generateDebugSources UP-TO-DATE
:CordovaLib:compileDebugJava UP-TO-DATE
:CordovaLib:processDebugJavaRes UP-TO-DATE
:CordovaLib:packageDebugJar UP-TO-DATE
:CordovaLib:compileDebugNdk UP-TO-DATE
:CordovaLib:packageDebugJniLibs UP-TO-DATE
:CordovaLib:packageDebugLocalJar UP-TO-DATE
:CordovaLib:packageDebugRenderscript UP-TO-DATE
:CordovaLib:bundleDebug UP-TO-DATE
:cordova-plugin-hotline:Hotline:compileLint
:cordova-plugin-hotline:Hotline:copyDebugLint UP-TO-DATE
:cordova-plugin-hotline:Hotline:preBuild
:cordova-plugin-hotline:Hotline:preDebugBuild
:cordova-plugin-hotline:Hotline:checkDebugManifest
:cordova-plugin-hotline:Hotline:preDebugTestBuild
:cordova-plugin-hotline:Hotline:prepareAndroidCordovaLibUnspecifiedDebugLibrary UP-TO-DATE
:CordovaLib:copyReleaseLint UP-TO-DATE
:CordovaLib:mergeReleaseProguardFiles UP-TO-DATE
:CordovaLib:preReleaseBuild
:CordovaLib:checkReleaseManifest
:CordovaLib:prepareReleaseDependencies
:CordovaLib:compileReleaseAidl UP-TO-DATE
:CordovaLib:compileReleaseRenderscript UP-TO-DATE
:CordovaLib:generateReleaseBuildConfig UP-TO-DATE
:CordovaLib:generateReleaseAssets UP-TO-DATE
:CordovaLib:mergeReleaseAssets UP-TO-DATE
:CordovaLib:generateReleaseResValues UP-TO-DATE
:CordovaLib:generateReleaseResources UP-TO-DATE
:CordovaLib:packageReleaseResources UP-TO-DATE
:CordovaLib:processReleaseManifest UP-TO-DATE
:CordovaLib:processReleaseResources UP-TO-DATE
:CordovaLib:generateReleaseSources UP-TO-DATE
:CordovaLib:compileReleaseJava UP-TO-DATE
:CordovaLib:processReleaseJavaRes UP-TO-DATE
:CordovaLib:packageReleaseJar UP-TO-DATE
:CordovaLib:compileReleaseNdk UP-TO-DATE
:CordovaLib:packageReleaseJniLibs UP-TO-DATE
:CordovaLib:packageReleaseLocalJar UP-TO-DATE
:CordovaLib:packageReleaseRenderscript UP-TO-DATE
:CordovaLib:bundleRelease UP-TO-DATE
:cordova-plugin-hotline:Hotline:preReleaseBuild
:cordova-plugin-hotline:Hotline:prepareComAndroidSupportAppcompatV72221Library UP-TO-DATE
:cordova-plugin-hotline:Hotline:prepareComAndroidSupportRecyclerviewV72221Library UP-TO-DATE
:cordova-plugin-hotline:Hotline:prepareComAndroidSupportSupportV42221Library UP-TO-DATE
:cordova-plugin-hotline:Hotline:prepareComGoogleAndroidGmsPlayServicesBase780Library UP-TO-DATE
:cordova-plugin-hotline:Hotline:prepareComGoogleAndroidGmsPlayServicesGcm780Library UP-TO-DATE
:cordova-plugin-hotline:Hotline:prepareDebugDependencies
:cordova-plugin-hotline:Hotline:compileDebugAidl UP-TO-DATE
:cordova-plugin-hotline:Hotline:compileDebugRenderscript UP-TO-DATE
:cordova-plugin-hotline:Hotline:generateDebugBuildConfig UP-TO-DATE
:cordova-plugin-hotline:Hotline:generateDebugAssets UP-TO-DATE
:cordova-plugin-hotline:Hotline:mergeDebugAssets UP-TO-DATE
:cordova-plugin-hotline:Hotline:generateDebugResValues UP-TO-DATE
:cordova-plugin-hotline:Hotline:generateDebugResources UP-TO-DATE
:cordova-plugin-hotline:Hotline:mergeDebugResources UP-TO-DATE
:cordova-plugin-hotline:Hotline:processDebugManifest UP-TO-DATE
:cordova-plugin-hotline:Hotline:processDebugResources UP-TO-DATE
:cordova-plugin-hotline:Hotline:generateDebugSources UP-TO-DATE
:cordova-plugin-hotline:Hotline:compileDebugJava UP-TO-DATE
:cordova-plugin-hotline:Hotline:extractDebugAnnotations UP-TO-DATE
:cordova-plugin-hotline:Hotline:mergeDebugProguardFiles UP-TO-DATE
:cordova-plugin-hotline:Hotline:processDebugJavaRes UP-TO-DATE
:cordova-plugin-hotline:Hotline:packageDebugJar UP-TO-DATE
:cordova-plugin-hotline:Hotline:compileDebugNdk UP-TO-DATE
:cordova-plugin-hotline:Hotline:packageDebugJniLibs UP-TO-DATE
:cordova-plugin-hotline:Hotline:packageDebugLocalJar UP-TO-DATE
:cordova-plugin-hotline:Hotline:packageDebugRenderscript UP-TO-DATE
:cordova-plugin-hotline:Hotline:packageDebugResources UP-TO-DATE
:cordova-plugin-hotline:Hotline:bundleDebug UP-TO-DATE
:prepareAndroidCordovaLibUnspecifiedDebugLibrary UP-TO-DATE
:prepareAndroidCordovaPluginHotlineHotlineUnspecifiedDebugLibrary UP-TO-DATE
:preReleaseBuild
:cordova-plugin-hotline:Hotline:copyReleaseLint UP-TO-DATE
:cordova-plugin-hotline:Hotline:checkReleaseManifest
:cordova-plugin-hotline:Hotline:prepareAndroidCordovaLibUnspecifiedReleaseLibrary UP-TO-DATE
:cordova-plugin-hotline:Hotline:prepareReleaseDependencies
:cordova-plugin-hotline:Hotline:compileReleaseAidl UP-TO-DATE
:cordova-plugin-hotline:Hotline:compileReleaseRenderscript UP-TO-DATE
:cordova-plugin-hotline:Hotline:generateReleaseBuildConfig UP-TO-DATE
:cordova-plugin-hotline:Hotline:generateReleaseAssets UP-TO-DATE
:cordova-plugin-hotline:Hotline:mergeReleaseAssets UP-TO-DATE
:cordova-plugin-hotline:Hotline:generateReleaseResValues UP-TO-DATE
:cordova-plugin-hotline:Hotline:generateReleaseResources UP-TO-DATE
:cordova-plugin-hotline:Hotline:mergeReleaseResources UP-TO-DATE
:cordova-plugin-hotline:Hotline:processReleaseManifest UP-TO-DATE
:cordova-plugin-hotline:Hotline:processReleaseResources UP-TO-DATE
:cordova-plugin-hotline:Hotline:generateReleaseSources UP-TO-DATE
:cordova-plugin-hotline:Hotline:compileReleaseJava UP-TO-DATE
:cordova-plugin-hotline:Hotline:extractReleaseAnnotations UP-TO-DATE
:cordova-plugin-hotline:Hotline:mergeReleaseProguardFiles UP-TO-DATE
:cordova-plugin-hotline:Hotline:processReleaseJavaRes UP-TO-DATE
:cordova-plugin-hotline:Hotline:packageReleaseJar UP-TO-DATE
:cordova-plugin-hotline:Hotline:compileReleaseNdk UP-TO-DATE
:cordova-plugin-hotline:Hotline:packageReleaseJniLibs UP-TO-DATE
:cordova-plugin-hotline:Hotline:packageReleaseLocalJar UP-TO-DATE
:cordova-plugin-hotline:Hotline:packageReleaseRenderscript UP-TO-DATE
:cordova-plugin-hotline:Hotline:packageReleaseResources UP-TO-DATE
:cordova-plugin-hotline:Hotline:bundleRelease UP-TO-DATE
:prepareComAndroidSupportAppcompatV72221Library UP-TO-DATE
:prepareComAndroidSupportRecyclerviewV72221Library UP-TO-DATE
:prepareComAndroidSupportSupportV42300Library UP-TO-DATE
:prepareComGoogleAndroidGmsPlayServicesBase840Library UP-TO-DATE
:prepareComGoogleAndroidGmsPlayServicesBasement840Library UP-TO-DATE
:prepareComGoogleAndroidGmsPlayServicesGcm840Library UP-TO-DATE
:prepareComGoogleAndroidGmsPlayServicesMeasurement840Library UP-TO-DATE
:prepareIoIntercomAndroidIntercomSdk113Library UP-TO-DATE
:prepareIoIntercomAndroidIntercomSdkBase113Library UP-TO-DATE
:prepareIoIntercomAndroidIntercomSdkGcm113Library UP-TO-DATE
:prepareDebugDependencies
:compileDebugAidl UP-TO-DATE
:compileDebugRenderscript UP-TO-DATE
:generateDebugBuildConfig UP-TO-DATE
:generateDebugAssets UP-TO-DATE
:mergeDebugAssets UP-TO-DATE
:generateDebugResValues UP-TO-DATE
:generateDebugResources UP-TO-DATE
:mergeDebugResources UP-TO-DATE
:processDebugManifest UP-TO-DATE
:processDebugResources UP-TO-DATE
:generateDebugSources UP-TO-DATE
:compileDebugJava
/media/media/Projects/MobileBinarySignals/MobileApp/BinarySignals/platforms/android/src/com/freshdesk/hotline/android/HotlineGcmRegistrationService.java:28: error: cannot find symbol
                String token = instanceID.getToken(senderId, GoogleCloudMessaging.INSTANCE_ID_SCOPE, null);
                                                                                 ^
  symbol:   variable INSTANCE_ID_SCOPE
  location: class GoogleCloudMessaging
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
1 error

 FAILED

FAILURE: Build failed with an exception.
- What went wrong:
  Execution failed for task ':compileDebugJava'.
  
  > Compilation failed; see the compiler error output for details.
- Try:
  Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 2.158 secs`

**Comment by rsquare2014** [comment]
Did you include or change the play services library?

**Comment by sisodiakaran** [comment]
Yes I have included Play Services Library.

**Comment by rsquare2014** [comment]
can you tell me the version number?

**Comment by sisodiakaran** [comment]
Its `play-services:9.0.2`

**Comment by rsquare2014** [comment]
Do you add [playservices plugin](https://www.npmjs.com/package/cordova-plugin-googleplayservices) to your project?
Or if you have a package.json please share the same.

**Comment by sisodiakaran** [comment]
Resolved the issue by updating `cordova-plugin-googleplayservices` to `Version 19.0.3`.

**Comment by rsquare2014** [comment]
Alright. I am closing the issue
