### ISSUE TITLE
FileProvider for Hotline 

### ISSUE THREAD

**Issue by maxdimaz** [freshdesk/hotline-phonegap#30]
Hi today i got this message 

"Missing/Bad FileProvider for Hotline. Camera capture will fail in devices running Nougat or later versions of OS (error code 354)"

How to fix that on phonegap project i was search and only found this one 
https://support.hotline.io/support/solutions/articles/221188-hotline-android-sdk-integration-steps

**Comment by rsquare2014** [comment]
Hey,

    As in Section no 1.1 in the link you shared you need to add
`<provider
    android:name="android.support.v4.content.FileProvider"
    android:authorities="com.example.demoapp.provider"
    android:exported="false"
    android:grantUriPermissions="true">
    <meta-data
        android:name="android.support.FILE_PROVIDER_PATHS"
        android:resource="@xml/hotline_file_provider_paths" />
</provider>`

In your AndroidManifest.xml file.

 and in your Strings.xml file add
`<string name="hotline_file_provider_authority">com.example.demoapp.provider</string>`
 
Don't forget to replace "com.example.demoapp." in the authorities attribute and in the strings file with your app's package name

**Comment by maxdimaz** [comment]
I was do it, here result of decompile my apk using apktool

AndroidManifest.xml (Some Tag)
`<uses-feature android:name="android.hardware.camera" android:required="true"/>
    <provider android:authorities="id.tested.android.provider" android:exported="false" android:grantUriPermissions="true" android:name="android.support.v4.content.FileProvider">
        <meta-data android:name="android.support.FILE_PROVIDER_PATHS" android:resource="@xml/hotline_file_provider_paths"/>
    </provider>
    <uses-permission android:name="android.permission.RECORD_AUDIO"/>`

here is my string.xml
`<string name="hotline_error_no_matching_solution_categories_found">No matching FAQ categories found !</string>
    <string name="hotline_file_provider_authority">id.tested.android.provider</string>
    <string name="hotline_hint_compose_message">Type a message</string>`

still got that message anyother solutions?

**Comment by maxdimaz** [comment]
FIX : 

add `<provider>`  inside `<application>`
