### ISSUE TITLE
Android App Crashed when FAQ clicked

### ISSUE THREAD

**Issue by jasonandress** [freshdesk/hotline-phonegap#34]
Same issue as issue #29 

Stack Trace error:
07-05 18:37:53.984  7673  7673 E AndroidRuntime: java.lang.UnsupportedOperationException: This is not supported, use MenuItemCompat.setOnActionExpandListener()
07-05 18:37:53.984  7673  7673 E AndroidRuntime:        at android.support.v7.internal.view.menu.MenuItemImpl.setOnActionExpandListener(MenuItemImpl.java:740)
07-05 18:37:53.984  7673  7673 E AndroidRuntime:        at android.support.v4.view.MenuItemCompat.setOnActionExpandListener(MenuItemCompat.java:363)
07-05 18:37:53.984  7673  7673 E AndroidRuntime:        at com.freshdesk.hotline.activity.ArticleListActivity.onCreateOptionsMenu(Unknown Source)
07-05 18:37:53.984  7673  7673 E AndroidRuntime:        at android.app.Activity.onCreatePanelMenu(Activity.java:3157)
07-05 18:37:53.984  7673  7673 E AndroidRuntime:        at android.support.v4.app.FragmentActivity.onCreatePanelMenu(FragmentActivity.java:320)
07-05 18:37:53.984  7673  7673 E AndroidRuntime:        at android.support.v7.internal.view.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:84)
07-05 18:37:53.984  7673  7673 E AndroidRuntime:        at android.support.v7.app.AppCompatDelegateImplBase$AppCompatWindowCallbackBase.onCreatePanelMenu(AppCompatDelegateImplBase.java:275)
07-05 18:37:53.984  7673  7673 E AndroidRuntime:        at android.support.v7.app.AppCompatDelegateImplV7.preparePanel(AppCompatDelegateImplV7.java:1117)
07-05 18:37:53.984  7673  7673 E AndroidRuntime:        at android.support.v7.app.AppCompatDelegateImplV7.doInvalidatePanelMenu(AppCompatDelegateImplV7.java:1399)
07-05 18:37:53.984  7673  7673 E AndroidRuntime:        at android.support.v7.app.AppCompatDelegateImplV7.access$100(AppCompatDelegateImplV7.java:89)
07-05 18:37:53.984  7673  7673 E AndroidRuntime:        at android.support.v7.app.AppCompatDelegateImplV7$1.run(AppCompatDelegateImplV7.java:126)
07-05 18:37:53.984  7673  7673 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:751)
07-05 18:37:53.984  7673  7673 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:95)
07-05 18:37:53.984  7673  7673 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:154)
07-05 18:37:53.984  7673  7673 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6154)
07-05 18:37:53.984  7673  7673 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
07-05 18:37:53.984  7673  7673 E AndroidRuntime:        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
07-05 18:37:53.984  7673  7673 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)

**Comment by jasonandress** [comment]
I did a little investigating and the issue was with cordova-plugin-local-notifications. Issue listed below. Basically they didn't pin the android.support version and it was picking up an alpha version. Instructions on how to fix are in the below issue from their repo.

https://github.com/katzer/cordova-plugin-local-notifications/issues/1322

**Comment by TraXex** [comment]
Hi, 
I am also facing same issue.  My app is building and hotline chat is working.
FAQ grid is shown but on clicking item it crashes. 

@jasonandress  pls let me know if you have taken additional steps to fix it. Thx.

**Comment by jasonandress** [comment]
I fixed it as described in my comment above. You may not have the local notice plugin. However any plugin that doesn't pin the android.support library will have this issue. 

Read the issue in the link I posted and review all of your plugins' plugin.xml for the issue. Then fix it as described.

**Comment by asiddeen** [comment]
@jasonandress thank you, it worked
