### ISSUE TITLE
Android Notification not received if I kill the app

### ISSUE THREAD

**Issue by swapnilagarwwal** [freshdesk/hotline-phonegap#8]
I am using the library on Mi3.
I am using `window.Hotline.registerPushNotification(<my-project-number>)` method
I immediately receive notification when the app is running in background, but I don't receive any notification if the app is killed.
Please help.

**Comment by hrishikesh-p** [comment]
we have changed how we handle push . Please refer to our docs here -> https://github.com/freshdesk/hotline-phonegap/blob/master/README.md

You will need to use  "phonegap-plugin-push"  instead of this method. Sorry for the inconvenience

**Comment by karansharma27** [comment]
phonegap-plugin-push doesnt work as I want. So I am using cordova-plugin-firebase. So isn't there any workaround for cordova-plugin-firebase.?
